
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- This configuration is split into one file per section (each a sibling of
-- this file), required below in the same order they used to appear here.

require("monitors")
require("programs")
require("autostart")
require("environment")
require("permissions")
require("appearance")
require("misc")
require("input")
require("keybindings")
require("windowrules")
