set-option -sg default-terminal "screen-256color"
set -g mouse on

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1
setw -g pane-base-index 1

# use vim motions to navigate panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# remember to install tpm https://github.com/tmux-plugins/tpm

# sets history limit to increased value
set-option -g history-limit 5000

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible' # optional recommended

set -g @plugin 'egel/tmux-gruvbox'
# set desired theme options...

# set date in US notation
set -g @tmux-gruvbox 'dark256' # or 'dark256', 'light', 'light256'
set -g @tmux-gruvbox-right-status-x '%m/%d/%Y' # e.g.: 01/31/2024
# set US time format
set -g @tmux-gruvbox-right-status-y '%I:%M %p' # 09:54 PM
set -g status-left '#S#{?#{>:#{session_windows},1}, [#{session_windows}w],} '

set -g status-position top

# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
